#!/bin/bash

while IFS= read -r line; do
	if [ -n "$line" ]; then
		echo "# $line"
		cat $1 | grep "$line"
		echo ""
	fi
done < <(cat $1 |\
# Generate domains (example.com) from full URLs (http://example.com/sub/folder/name/)
	# Remove everything until the URL
	sed 's/\(.*](http[s]*:\/\/\)\(.*\)/\2/' |\
	# Remove subfolder(s) from the URL
	sed 's/\([^\/]*\)\(\/\)\(.*\)/\1/' |\
	# Remove subdomain - comment line if it should be kept
	sed 's/\([^.]\{1,\}\)\([.]\{1\}\)\([^.]\{1,\}\)\(.\)\([.]\{1\}\)/\3\4\5/' |\
	# Sort result
	sort |\
	# Keep unique lines only
	uniq)
